version: '3'

services:
  adconvert-shop:
    container_name: adconvert-shop-container
    image: adconvert-shop-img
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Map localhost:3000 to container:3000
    env_file:
      - .env
